# Generated by Django 5.2.3 on 2025-07-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='otp_secret',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
